apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins-ns
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
      - name: jenkins-app
        image: alyghazal22/jenkins:v1.2
        securityContext:
          privileged: true
        ports:
          - name: http-port
            containerPort: 8080
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins-vol
          - name: dockersock
            mountPath: /var/run/
      volumes:
        - name: jenkins-vol
          hostPath:
            path: /var/jenkins-vol
        - name: dockersock
          hostPath:
            path: /var/run/


